apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: current-time
  labels:
    app: current-time
spec:
  selector:
    matchLabels:
      app: current-time
  replicas: 2
  template:
    metadata:
      labels:
        app: current-time
    spec:
      containers:
      - name: current-time
        image: docker.io/tinrab/tutorial
        command: ["current-time"]
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: current-time
spec:
  type: NodePort
  selector:
    app: current-time
  ports:
  - port: 3000
